apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-pod
  template:
    metadata:
      labels:
        app: todo-pod
    spec:
      containers:
        - name: todo-pod
          image: dupalli/g1-to-do-app:v1
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
               path: /
               port: 80
            initialDelaySeconds: 180
            periodSeconds: 3
          livenessProbe:
            httpGet:
               path: /
               port: 80
            initialDelaySeconds: 180
            periodSeconds: 3