apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: manuelleppertt/todo_app:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
               path: /
               port: 3000
            initialDelaySeconds: 30
          periodSeconds: 3
            livenessProbe:
            httpGet:
               path: /
               port: 3000
            initialDelaySeconds: 30
            periodSeconds: 3